
### Admin mette tipi di biglietti
POST http://localhost:8082/admin/tickets/
X-XSRF-TOKEN: 224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Content-Type: application/json
Cookie: XSRF-TOKEN=224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A

{
  "type": "Settimanale",
  "price": 10
}


### Visita al catalogo bigleitti

GET http://localhost:8082/tickets/


### Admin acquista biglietti

POST http://localhost:8082/shop/1/
X-XSRF-TOKEN: 224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Content-Type: application/json
Cookie: XSRF-TOKEN=224159f4-d4ed-41ff-b726-c6d7a2ad71d6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJCaWdCb3NzIiwiaWF0IjoxNjUyNDU2MjQ5LCJleHAiOjE5MjQ5MDU2MDAsInJvbGVzIjpbIkFETUlOIl19.z8RClg7GgpT4e-OjihMJbflIWiDxzrdrYNhL2HteE_A

{
  "ticketId": 1,
  "numOfTickets": 10,
  "paymentInfo": {
    "creditCardNumber": "1234-4567-8901-2345",
    "exp": "2030-01-01",
    "csv": "123"
  }
}

